### Execute a random endpoint
GET http://localhost:8080/open-l4d
###

### 1) Ask for next invocation
GET http://localhost:8081/2018-06-01/runtime/invocation/next

> {%
  const requestId = response.body.requestContext.requestId;
  client.global.set("requestId", requestId);
  client.log("requestId=" + requestId);
%}

### 2) Send function response using captured requestId
POST http://localhost:8081/runtime/invocation/{{requestId}}/response
Content-Type: application/json

{
  "statusCode": 200,
  "headers": {
    "content-type": "application/json"
  },
  "body": "{\"ok\":true}",
  "isBase64Encoded": false,
  "cookies": []
}

### 3) Send a runtime error using captured requestId
POST http://localhost:8081/runtime/invocation/{{requestId}}/error
Content-Type: application/json

{
  "errorMessage": "This is a runtime error",
  "errorType": "Runtime.UnknownReason",
  "stackTrace": [
    "line 123123",
    "line 456456"
  ]
}